apiVersion: "kubeovn.ustc.io/v1"
kind: VpcNatTunnel
metadata:
  name: ovn-gre0
  namespace: ns1
spec:
  remoteIp: "10.10.0.21" #互联的对端vpc网关实体网络ip
  interfaceAddr: "10.100.0.1/24" #隧道地址
  natGwDp: "gw1" #vpc网关名字
  remoteGlobalnetCIDR: "242.0.0.0/16"
