# permissions for end users to view gatewayexips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gatewayexip-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubeovn-multivpc
    app.kubernetes.io/part-of: kubeovn-multivpc
    app.kubernetes.io/managed-by: kustomize
  name: gatewayexip-viewer-role
rules:
- apiGroups:
  - kubeovn.ustc.io
  resources:
  - gatewayexips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeovn.ustc.io
  resources:
  - gatewayexips/status
  verbs:
  - get
