# permissions for end users to edit vpcdnsforwards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vpcdnsforward-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubeovn-multivpc
    app.kubernetes.io/part-of: kubeovn-multivpc
    app.kubernetes.io/managed-by: kustomize
  name: vpcdnsforward-editor-role
rules:
- apiGroups:
  - kubeovn.ustc.io
  resources:
  - vpcdnsforwards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeovn.ustc.io
  resources:
  - vpcdnsforwards/status
  verbs:
  - get
