apiVersion: kubeovn.ustc.io/v1
kind: VpcNatTunnel
metadata:
  labels:
    app.kubernetes.io/name: kubeovn-multivpc
    app.kubernetes.io/managed-by: kustomize
  name: vpcnattunnel-sample
spec:
  # TODO(user): Add fields here
